In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import fcluster, linkage





In [2]:
data = {
    "x": [1.0, 1.1, 2.5, 2.6, 5.0, 5.1, 5.5],
    "y": [1.0, 1.2, 2.5, 2.6, 5.0, 5.2, 5.5],
}
df = pd.DataFrame(data)

In [3]:
df

x    y
0  1.0  1.0
1  1.1  1.2
2  2.5  2.5
3  2.6  2.6
4  5.0  5.0
5  5.1  5.2
6  5.5  5.5

In [4]:
distance_matrix = pdist(df[['x', 'y']], metric='euclidean')

In [5]:
distance_matrix

array([0.2236068 , 2.12132034, 2.2627417 , 5.65685425, 5.86941224,
       6.36396103, 1.91049732, 2.05182845, 5.44518136, 5.65685425,
       6.15223537, 0.14142136, 3.53553391, 3.74833296, 4.24264069,
       3.39411255, 3.60693776, 4.10121933, 0.2236068 , 0.70710678,
       0.5       ])

In [7]:
linkage_matrix = linkage(distance_matrix, method='single')

In [8]:
linkage_matrix


array([[ 2.        ,  3.        ,  0.14142136,  2.        ],
       [ 0.        ,  1.        ,  0.2236068 ,  2.        ],
       [ 4.        ,  5.        ,  0.2236068 ,  2.        ],
       [ 6.        ,  9.        ,  0.5       ,  3.        ],
       [ 7.        ,  8.        ,  1.91049732,  4.        ],
       [10.        , 11.        ,  3.39411255,  7.        ]])

In [11]:
clusters = fcluster(linkage_matrix, t=0.5, criterion='distance')
clusters

array([4, 4, 3, 3, 1, 1, 2], dtype=int32)

In [12]:
df['cluster'] = clusters

In [13]:
df

x    y  cluster
0  1.0  1.0        4
1  1.1  1.2        4
2  2.5  2.5        3
3  2.6  2.6        3
4  5.0  5.0        1
5  5.1  5.2        1
6  5.5  5.5        2